# https://github.com/Powerlevel9k/powerlevel9k/wiki/Install-Instructions#step-1-install-powerlevel9k
# git clone https://github.com/bhilburn/powerlevel9k.git ~/.oh-my-zsh/custom/themes/powerlevel9k
ZSH_THEME="powerlevel9k/powerlevel9k"

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir rbenv vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()
POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
POWERLEVEL9K_SHORTEN_DELIMITER=

#POWERLEVEL9K_USER_DEFAULT_FOREGROUND='248'
#POWERLEVEL9K_USER_DEFAULT_BACKGROUND='247'
#POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='076'
#POWERLEVEL9K_DIR_HOME_BACKGROUND='076'
#POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='076'
